spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contus_db
    username: springstudent
    password: springstudent
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: CONTUS-APPLICATION

